improve close port operation

diff --git a/qemu-forward b/qemu-forward
--- a/qemu-forward
+++ b/qemu-forward
@@ -210,8 +210,10 @@ _add_rule() { #{{{
       _error "opening port failed. $DETAIL"
       return $RET
     fi
+  else
+    local WILL='will be '
   fi
-  _log "${C_GREEN}port opened.${C_OFF} $DETAIL"
+  _log "${C_GREEN}port ${WILL}opened.${C_OFF} $DETAIL"
 
   return 0
 }
@@ -273,12 +275,12 @@ _delete_rule_iptables() { #{{{
 
 _delete_rule() { #{{{
   local GUEST_NAME="$1"
-  local ZONE="$2"
+  local OUT_IF="$2"
   local PROTO="$3"
   local HOST_PORT="$4"
   local GUEST_IP_ADDR="$5"
   local GUEST_PORT="$6"
-  local OUT_IF="$7"
+  local ZONE="$7"
 
   local RET=0
   local DETAIL=''
@@ -287,7 +289,7 @@ _delete_rule() { #{{{
   if [[ "${FIREWALL_CMD}" ]]; then
     _delete_rule_firewall_cmd ${ZONE} ${PROTO} ${HOST_PORT} ${GUEST_IP_ADDR} ${GUEST_PORT}
     local RET=$?
-    [[    RE  -eq 0 ]] && return $RET
+    [[ ! $RET -eq 0 ]] && return $RET
   #else
   #  _add_rule_iptables ${PROTO} eth0 ${HOST_PORT} ${GUEST_IP_ADDR} ${GUEST_PORT}
   #  local RET=$?
@@ -295,30 +297,57 @@ _delete_rule() { #{{{
   fi
 
   # delete iptables rule
-  local DELETED=''
-  DETAIL="interface:${OUT_IF} destination:${GUEST_IP_ADDR}:${GUEST_PORT}/${PROTO}"
-  ${IPTABLES} -t filter -nvL FORWARD --line-numbers | sed -re '1,2d' \
-    | while read NUM PKTS BYTES TARGET PROT OPT IN OUT SRC DST ACTION; do
-    [ "$DRY_RUN" ] && echo "  Checking... $NUM $TARGET $PROT $OPT $IN $OUT $SRC $DST $ACTION"
-    if [ "$DST" = "$GUEST_IP_ADDR" ] && [ "$TARGET" = "ACCEPT" ] && \
-      WARD --line-numbers
-      [[ "$ACTION" =~ .*${PROTO}\ dpt:${GUEST_PORT}$ ]]; then
+  local DELETED=
+  local DETAIL="interface:${OUT_IF} destination:${GUEST_IP_ADDR}:${GUEST_PORT}/${PROTO}"
+  while read _NUM _PKTS _BYTES _TARGET _PROT _OPT _IN _OUT _SRC _DST _ACTION; do
+    [[ "$DRY_RUN" ]] && echo "  Checking... $_NUM $_TARGET $_PROT $_OPT $_IN $_OUT $_SRC $_DST $_ACTION"
+    if [[ "$_DST" = "$GUEST_IP_ADDR" ]] && [[ "$_TARGET" = "ACCEPT" ]] && \
+      [[ "$_PROT" = "$PROTO" ]] && [[ "$_OUT" = "$OUT_IF" ]] && \
+      [[ "$_ACTION" =~ .*${PROTO}\ dpt:${GUEST_PORT}$ ]]; then
 
-      local RULE="$NUM $TARGET $PROT $OPT $IN $OUT $SRC $DEST $ACTION"
-      if [ ! "$DRY_RUN" ]; then
-        ${IPTABLES} -t filter -D FORWARD "$NUM"; RET=$?
-        if [ "$RET" -eq 0 ]; then
+      local RULE="$_NUM $_TARGET $_PROT $_OPT $_IN $_OUT $_SRC $_DEST $_ACTION"
+      if [[ ! "$DRY_RUN" ]]; then
+        ${IPTABLES} -t filter -D FORWARD "$_NUM"; RET=$?
+        if [[ "$RET" -eq 0 ]]; then
           _log "${C_GREEN}rule deleted.${C_OFF} $DETAIL $ACTION"  
           DELETED=yes
         else
           _error "delete rule failed. $DETAIL $ACTION"
         fi
+        break
       else
         _log "${C_GREEN}iptables rule will delete.${C_OFF} : $RULE"
         DELETED=yes
+        break
       fi
     fi
-  done
+  done < <(${IPTABLES} -t filter -nvL FORWARD --line-numbers | sed -re '1,2d')
+
+  # delete iptables rule
+  #local DELETED=''
+  #DETAIL="interface:${OUT_IF} destination:${GUEST_IP_ADDR}:${GUEST_PORT}/${PROTO}"
+  #${IPTABLES} -t filter -nvL FORWARD --line-numbers | sed -re '1,2d' \
+  #  | while read NUM PKTS BYTES TARGET PROT OPT IN OUT SRC DST ACTION; do
+  #  [[ "$DRY_RUN" ]] && echo "  Checking... $NUM $TARGET $PROT $OPT $IN $OUT $SRC $DST $ACTION"
+  #  if [[ "$DST" = "$GUEST_IP_ADDR" ]] && [[ "$TARGET" = "ACCEPT" ]] && \
+  #    [[ "$PROT" = "$PROTO" ]] && [[ "$OUT" = "$OUT_IF" ]] && \
+  #    [[ "$ACTION" =~ .*${PROTO}\ dpt:${GUEST_PORT}$ ]]; then
+
+  #    local RULE="$NUM $TARGET $PROT $OPT $IN $OUT $SRC $DEST $ACTION"
+  #    if [[ ! "$DRY_RUN" ]]; then
+  #      ${IPTABLES} -t filter -D FORWARD "$NUM"; RET=$?
+  #      if [[ "$RET" -eq 0 ]]; then
+  #        _log "${C_GREEN}rule deleted.${C_OFF} $DETAIL $ACTION"  
+  #        DELETED=yes
+  #      else
+  #        _error "delete rule failed. $DETAIL $ACTION"
+  #      fi
+  #    else
+  #      _log "${C_GREEN}iptables rule will delete.${C_OFF} : $RULE"
+  #      DELETED=yes
+  #    fi
+  #  fi
+  #done
 
   [[ ! "$DELETED" ]] && _log "${C_YELLOW}rule is not dound.${C_OFF} : $DETAIL"
   return 0
@@ -412,7 +441,7 @@ while read DOMAIN_NAME ZONE SOURCE DESTINATION DEST_IF; do
       _add_rule "$TARGET_GUEST_NAME" "$DEST_IF" "$PROTO" "$SRC_PORT" "$DEST_IP" "$DEST_PORT" "$ZONE"
       ;;
     stopped)
-      _delete_rule "$TARGET_GUEST_NAME" "$ZONE" "$PROTO" "$SRC_PORT" "$DEST_IP" "$DEST_PORT" "$DEST_IF"
+      _delete_rule "$TARGET_GUEST_NAME" "$DEST_IF" "$PROTO" "$SRC_PORT" "$DEST_IP" "$DEST_PORT" "$ZONE"
       ;;
   esac
 done < "$CONF_FILE"
